### ISSUE TITLE
Selecting items in SCB-Container: Doesn't deselect

### ISSUE THREAD

**Issue by noahtallen** [StopClickBait/SCB-NewExtension#1]
In the SCB-Container .html, when clicking one element in the list, it highlights blue. When selecting a different item, it also highlights and both are highlighted. This is true in both Chrome and Edge. You can deselect the item by clicking it again.

**Comment by autinerd** [comment]
This is okay, because the blue highlighting is going to be the indicator that the user voted up the item.
